# Generated by Django 3.2.5 on 2021-07-13 22:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('category', models.CharField(choices=[], max_length=50, verbose_name='Categoria')),
                ('reading_status', models.CharField(choices=[('unread', 'Não lido'), ('reading', 'Lendo'), ('read', 'Lido')], max_length=20, verbose_name='Status da leitura')),
                ('about', models.TextField(verbose_name='Sobre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
                ('authors', models.ManyToManyField(to='webapp.Author', verbose_name='Autor(es)')),
            ],
            options={
                'verbose_name': 'Livro',
            },
        ),
    ]
