# Generated by Django 3.2.5 on 2021-07-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reading_status',
            field=models.CharField(choices=[('unread', 'Não lido'), ('reading', 'Lendo'), ('read', 'Lido')], default='unread', max_length=20, verbose_name='Status da leitura'),
        ),
    ]
