# Generated by Django 3.2.5 on 2021-07-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_reading',
            field=models.DateField(blank=True, null=True, verbose_name='Data da última leitura (mês)'),
        ),
    ]
