# Generated by Django 3.2.5 on 2021-07-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_book_last_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.FileField(null=True, upload_to='photos/authors'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.FileField(null=True, upload_to='photos/covers'),
        ),
    ]
