# Generated by Django 3.2.5 on 2021-07-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20210714_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='about',
            field=models.TextField(blank=True, verbose_name='Sobre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='photos/covers', verbose_name='Capa'),
        ),
    ]
