# Generated by Django 3.2.5 on 2021-07-15 15:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210714_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mine', models.BooleanField(default=True, verbose_name='O livro é meu')),
                ('date', models.DateField(blank=True, default=datetime.datetime(2021, 7, 15, 12, 33, 18, 383059), null=True, verbose_name='Data')),
                ('estimated_return_date', models.DateField(blank=True, null=True, verbose_name='Data estimada para devolução')),
                ('status', models.CharField(choices=[('lent', 'Emprestado'), ('returned', 'Devolvido')], default='lent', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book', to='webapp.book', verbose_name='Livro')),
            ],
            options={
                'verbose_name': 'Empréstimo',
            },
        ),
    ]
